package com.logolsp.parser

data class Token(
    val type: TokenType,
    val value: String,
    val line: Int,
    val col: Int,
) {
    val endCol: Int get() = col + value.length
}

enum class TokenType {
    TO, END,
    IF, IFELSE,
    REPEAT,
    MAKE, LOCALMAKE,
    OUTPUT,
    STOP,
    LOCAL,
    FOR, WHILE, UNTIL, FOREVER,
    FOREACH, APPLY,
    RUN,
    TEST, IFTRUE, IFFALSE,
    NAME, THING,
    CATCH, THROW,

    BUILTIN,

    COLON_WORD,
    QUOTED_WORD,
    NUMBER,
    IDENTIFIER,

    PLUS, MINUS, STAR, SLASH, PERCENT,
    EQ, NEQ, LT, GT, LTE, GTE,

    LPAREN, RPAREN,
    LBRACKET, RBRACKET,
    LBRACE, RBRACE,

    COMMENT,
    NEWLINE,
    EOF,
    ERROR,
}

val KEYWORDS: Map<String, TokenType> = mapOf(
    "TO" to TokenType.TO,
    "END" to TokenType.END,
    "IF" to TokenType.IF,
    "IFELSE" to TokenType.IFELSE,
    "REPEAT" to TokenType.REPEAT,
    "MAKE" to TokenType.MAKE,
    "LOCALMAKE" to TokenType.LOCALMAKE,
    "OUTPUT" to TokenType.OUTPUT,
    "OP" to TokenType.OUTPUT,
    "STOP" to TokenType.STOP,
    "LOCAL" to TokenType.LOCAL,
    "FOR" to TokenType.FOR,
    "WHILE" to TokenType.WHILE,
    "UNTIL" to TokenType.UNTIL,
    "FOREVER" to TokenType.FOREVER,
    "FOREACH" to TokenType.FOREACH,
    "APPLY" to TokenType.APPLY,
    "RUN" to TokenType.RUN,
    "TEST" to TokenType.TEST,
    "IFTRUE" to TokenType.IFTRUE,
    "IFT" to TokenType.IFTRUE,
    "IFFALSE" to TokenType.IFFALSE,
    "IFF" to TokenType.IFFALSE,
    "NAME" to TokenType.NAME,
    "THING" to TokenType.THING,
    "CATCH" to TokenType.CATCH,
    "THROW" to TokenType.THROW,
)

val BUILTINS: Set<String> = setOf(
    "FORWARD", "FD", "BACK", "BK", "RIGHT", "RT", "LEFT", "LT", "HOME",
    "CLEARSCREEN", "CS", "CLEAN", "WRAP", "FENCE", "WINDOW",
    "SETBACKGROUND", "SETSCREENCOLOR", "SETSC", "BACKGROUND", "BG",
    "PENDOWN", "PD", "PENUP", "PU", "PENPAINT", "PPT", "PENERASE", "PE", "PENREVERSE", "PX",
    "SETPENCOLOR", "SETPC", "SETPENSIZE", "SETPW", "PENCOLOR", "PC", "PENSIZE", "PENMODE",
    "PENDOWNP",
    "SHOWTURTLE", "ST", "HIDETURTLE", "HT", "SHOWNP",
    "SETPOS", "SETXY", "SETX", "SETY", "SETHEADING", "SETH", "TOWARDS",
    "POS", "XCOR", "YCOR", "HEADING",
    "ARC", "FILL", "FILLED", "LABEL", "SETLABELHEIGHT", "SETLABELFONT",
    "SUM", "DIFFERENCE", "PRODUCT", "QUOTIENT", "REMAINDER", "MODULO",
    "ABS", "INT", "ROUND", "SQRT", "EXP", "LN", "LOG10", "LOG", "POWER",
    "SIN", "COS", "TAN", "ARCSIN", "ARCCOS", "ARCTAN", "ARCTAN2",
    "RADSIN", "RADCOS", "RADTAN",
    "PI", "RANDOM", "RERANDOM",
    "AND", "OR", "NOT", "XOR", "TRUE", "FALSE",
    "EQUALP", "NOTEQUALP", "LESSP", "GREATERP", "LESSEQUALP", "GREATEREQUALP",
    "WORDP", "LISTP", "ARRAYP", "NUMBERP", "EMPTYP", "MEMBERP", "SUBSTRINGP",
    "PROCEDUREP", "PRIMITIVEP", "DEFINEDP", "NAMEP",
    "WORD", "LIST", "SENTENCE", "SE", "FPUT", "LPUT",
    "FIRST", "LAST", "BUTFIRST", "BF", "BUTLAST", "BL",
    "ITEM", "COUNT", "ARRAY", "ARRAYTOLIST", "LISTTOARRAY",
    "PUSH", "POP", "QUEUE", "DEQUEUE",
    "UPPERCASE", "LOWERCASE", "CHAR", "ASCII",
    "PRINT", "PR", "SHOW", "TYPE", "READLIST", "RL", "READWORD",
    "CLEARTEXT", "CT",
    "CONTENTS", "PROCEDURES", "GLOBALS", "NAMES", "PRIMITIVES",
    "ERASE", "ERALL", "ERPS", "ERNS", "BURY", "BURYALL", "UNBURY", "UNBURYALL",
    "ARITY",
    "PPROP", "GPROP", "REMPROP", "PLIST",
    "SETTURTLES", "TELL", "ASKALL", "ASK", "TURTLE", "TURTLES",
    "REPCOUNT", "IGNORE", "MINUS",
    "SPLITSCREEN", "FULLSCREEN", "TEXTSCREEN",
    "STANDOUT", "CURSOR", "SETCURSOR", "READCHAR", "RC",
    "WAIT", "SETTURTLE",
    "REDUCE", "MAP", "FILTER", "FIND", "MAP.SE",
    "CROSSMAP", "REMDUP", "PICK",
    "CASCADE", "DOTIMES",
)
